# Generated by Django 3.1.4 on 2021-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20210320_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['watched', '-date_added']},
        ),
        migrations.AlterField(
            model_name='item',
            name='imdbid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
