# Generated by Django 3.1.4 on 2021-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20210327_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imdbid',
            field=models.CharField(max_length=20),
        ),
    ]
