# Generated by Django 3.1.4 on 2021-01-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviechoice',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
    ]
