# Generated by Django 3.1.4 on 2021-01-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0002_moviechoice_runtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieChoice',
        ),
    ]
